### ISSUE TITLE
PowerCLI 5.1 Release 2 and newer fails to retrieve metadata values

### ISSUE THREAD

**Issue by robcoward** [skyscape-cloud-services/AutoStartStop#2]
From the release of PowerCLI 5.1 Release 2 onwards, the code in these powershell scripts that retrieve metadata values for the VM/vApps is broken. The underlying PowerCLI will return a list of the metadata key/value pairs, but all the values are blank.

These scripts have been tested and work with PowerCLI 5.1 Release 1 (build 793510), but unfortunately that version no longer appears to be available to download from VMWare's website.

@ob2756 an alternative method of retrieving VM/vApp metadata key/value pairs needs to be found to support newer PowerCLI installations.

**Comment by robcoward** [comment]
http://kiwicloud.ninja/2016/02/working-with-vcloud-metadata-in-powercli-part-1/ and http://kiwicloud.ninja/2016/03/working-with-vcloud-metadata-in-powercli-part-2/ would appear to offer the answer. However in testing it out, rather than returning all the columns shown in the blog post, it only returns the Value and not the Key or the VM Name.

**Comment by robcoward** [comment]
PowerCLI 5.1 Release 1 can be downloaded from https://my.vmware.com/group/vmware/details?downloadGroup=VSP510-PCLI-510&productId=285

**Comment by tlawrence** [comment]
I think I've fixed this now. Could you test for me? Also regression test on the older version if you have it..

**Comment by ob2756** [comment]
![image](https://cloud.githubusercontent.com/assets/12936631/13773513/711d2f02-ea91-11e5-848e-dca88e1d843e.png)

Think so - i will have more time to test it later on or tomorrow.  I have got v6 and it powered on a vAPP, while displaying a UID warning.

**Comment by skips123** [comment]
I've just done the same but for a VM and it worked with the same warnings as noted above

**Comment by robcoward** [comment]
Looking at the underlying code change, it certainly returns the metadata correctly on PowerCLI 5.5 Release 2:
```powershell
PowerCLI C:\> $vm.ExtensionData.GetMetadata().MetadataEntry | select @{N="VM";E={$vm.Name}}, Key, @{N="value";E={$_.TypedValue.value}}

VM                                         Key                                       value
--                                         ---                                       -----
centos71                                   SkyscapeLocation                          Farnborough
centos71                                   AutoOnOff                                 Yes
centos71                                   StartTime                                 09
centos71                                   StopTime                                  17
centos71                                   Days                                      Every
```
and running the AutoPower VM.ps1 script results in my test VM powering up correctly,

Thanks for the fix @tlawrence

**Comment by robcoward** [comment]
I'll be merging #1 shortly to tidy up the documentation and get the script filenames consistent with the updates being made to the Blueprint document. I'll close this issue once everything is consistent.

**Comment by robcoward** [comment]
@tlawrence's use of $_.TypedValue.value does not work with PowerCLI 5.1 Release 1 so if we are to support older versions of PowerCLI then we will need to put some conditional logic in the powershell based on Get-PowerCLIVersion to retrieve the metadata values via the different methods.
